### ISSUE TITLE
On more online compiler - Comeau

### ISSUE THREAD

**Issue by myd7349** [fffaraz/awesome-cpp#160]
Comeau: http://www.comeaucomputing.com/tryitout/

**Comment by jpetso** [comment]
Personally, I have a hard time seeing what benefit this one can offer over the other online compilers in the list - it looks more of a sales lead generation form than a tool to help developers. Moreover, the current compiler version was not updated since October 2008 [according to Wikipedia](https://en.wikipedia.org/wiki/Comeau_C/C%2B%2B). What makes this one "awesome"?
