### ISSUE TITLE
david-a-wheeler/flawfinder

### ISSUE THREAD

**Issue by fffaraz** [fffaraz/awesome-cpp#607]
https://github.com/david-a-wheeler/flawfinder

**Comment by eXpl0it3r** [comment]
So it just searches for function names in a list and if it matches it tells you that maybe there's a risk? That's the kind of "security" scanning government loves, because they get to understand it, but it's also the least useful analyzer.

It's 12 years old (with lots of change in recent years) and has 2 stars, how awesome is it really? 😉
